language: R
sudo: required
cache: packages

apt_packages:
  - libudunits2-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - seb@poissonconsulting.ca
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always
